[package]
name = "debug-traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.5.6"

[dependencies.defmt]
optional = true
version = ">=0.2.3,<0.4.0"
